### ISSUE TITLE
All Status-Led's blinking indefinitly after conntecting (original) DS3 over bluetooth

### ISSUE THREAD

**Issue by Blightbuster** [nefarius/Shibari#10]
# Reproduce
1. Reset DS3 (not sure if nescessary but I always do to turn the DS3 off)
2. Press PS-Button to turn it on

# Observed Behaviour
Controller connects after a while and all status-led's keep blinking

# Expected behaviour
After connecting only the appropriate led should be lit

---

##### Im not sure if this is intended / out of scope or if this even is a problem of Shibari and not the driver.

**Comment by nefarius** [comment]
The LEDs of a DS3 keep blinking if it doesn't understand/accept or receives the packet setting the LED and vibration motors properly. I unfortunately don't know why this happens on some models, in this case it's a Shibari issue.

**Comment by Blightbuster** [comment]
The weird thing is, that it wasnt an issue right after I installed the driver and Shibari. It only started hapening after disconnecting and then reconnecting the controller. I will try to reproduce this soon.

**Comment by nefarius** [comment]
See #18
