### ISSUE TITLE
Controller not working until I unplug/replug usb

### ISSUE THREAD

**Issue by UltraJohn** [nefarius/Shibari#13]
**Describe the bug**
I'm using a ps3 controller with ViGEm/Shibari/Fireshock. The first week I had no issues, but now every time i reboot my pc my controller does not work until i unplug the usb and plug it back in. I have checked that the shibari dom server is running (it is) and have even tried reinstalling all the drivers.

**To Reproduce**
Installed ViGEm, Shibari dom server with automatic service startup enabled in Windows, and Fireshock.
Reboot pc with usb cable plugged in. Controller is not working until I unplug the usb and plug it back in.

**Expected behavior**
The controller should automatically work after reboot.

**System details (please complete the following information):**
 - OS: Windows 10 19041.746
 - Feeder software: ViGEm, Shibari, Fireshock
 - Driver Version: ViGEm 1.17.333, Shibari 1.6.180, Fireshock 3.0.0.0

Edit: I did some more testing, and it's actually only on manually turning off pc, and turning it back on that it doesn't work. Using the reboot option causes the controller to work fine. Could this be caused by windows itself, e.g. maybe fast boot which only activates on shutting down, not reboots? Just a guess to why it might happen though.

Edit 2: Well I tried disabling fast boot and then turning off/on my pc and now the controller is working as intended. This leads me to believe there might be a problem with one of the drivers not loading properly in fast boot.

**Comment by nefarius** [comment]
See #18
