### ISSUE TITLE
Controller Freezes on input

### ISSUE THREAD

**Issue by Cyberb28** [nefarius/Shibari#15]
Describe the bug:

On older hardware computers your controller tends to freeze, I noticed because I was using a older computer and was experiencing constant freezing, I went onto my more powerful computer had no issues and once running a stress test my controller froze. 

**To Reproduce**
Steps to reproduce the behavior (example):
1.) Start the program
2.) Use a controller and plug it in
3.) run a stress test
4.) Controller freezes

**Expected behavior**
I am not quite sure what Im supposed to put here but maybe optimize the emulation software for older computers and that could possibly lessen the freezing if not stop it 

**System details (please complete the following information):**
 - OS: [Windows 10 Pro 20H2
 - Feeder software: Dualsense Controller CFI-ZCT1W
 - Driver Version: 1.17.333

**Additional context**
I noticed that this version only supports windows 10 so I am curious over whether or not if I used a older version of ViGEmBus would help.

**Comment by nefarius** [comment]
See #18
