### ISSUE TITLE
Charging controller

### ISSUE THREAD

**Issue by joaogrande10** [nefarius/Shibari#17]
Sorry to ask that, but I wish to know if the symbol besides controller 1 means that it is charging. I want to know if there is any way to charge the controller on PC. And just for the record, when a bunch of [?????] shows instead of the bar, what is the meaning? I'm sorry for my bad english
![image](https://user-images.githubusercontent.com/55845765/110039464-03bbd900-7d20-11eb-8593-8edaa439f66d.png)

**Comment by nefarius** [comment]
Yes, that is a primitive charging animation. If it cycles to fill the bar it means it's charging. If there are question marks it could mean 2 things: the charge value couldn't be read, or your console encoding is not supporting the characters used for the animation.

Cheers

**Comment by joaogrande10** [comment]
Thank you very much, Nefarius. This is such a great work of yours! Conrgrats, man!

**Comment by nefarius** [comment]
See #18
