### ISSUE TITLE
Dualshock 3 Analog button pad / Pressure sensitivity

### ISSUE THREAD

**Issue by Ghaleon4** [nefarius/Shibari#5]
**Is your feature request related to a problem? Please describe.**
Hello!!
I'm still stuck using an isolated copy of MotionInJoy's .dll combined with BetterDS3 to get analog button data.  I saw that Shibari supports this thing called "sinks"?  Why don't they have one for the DualShock 3 yet??

**Describe the solution you'd like**
Maybe I should have posted this in the Shibari GitHub repository, but perhaps there is something to be done at the layer that Vigem sits at to better support analog face buttons on the DS3?

**Describe alternatives you've considered**
My primary goal is to be able to play Metal Gear Solid 2 Substance PC using analog face buttons with less hassle.  As mentioned above, I have to go through some crazy loops to reassign one of my RStick axis to Square just so Xpadder can later interperet that axis as a series of keyboard inputs that the game will recognize.  So:
Square barely pressed - 'Slow'
Square further depressed - 'Action + Slow'
Square pressed all the way - 'Action'

All of this just so I can holster my pistol after acquiring a target -but without having to unequip the stupid thing.  This is also necessary if you want to be able to aim with a rifle -otherwise, the thing just fires on full-auto as *soon* as you begin aiming.

I mean, it's miracle that I got this working as well as I did, but I *still* have to sacrifice an axis that would later have been used for 'Vertical Slice' when you get the sword!!

Jesus, if this is in the wrong place, someone send it to the right people.  This game is a masterpiece on PC but noone plays it because of all this...!

**Comment by nefarius** [comment]
Hello!

I took liberty to move you over here since that's not really a topic for ViGEmBus and alike 😃 

Since I don't really know the game; how is it *supposed* to be played? Which controllers and axes are natively supported and how do you want it?

You can hop onto Discord as well if you wish. Cheers.

**Comment by philbertasusa** [comment]
providing a method to expose the analog values for the pressure sensitive buttons(the d-pad, L1,L2 and the 4 face buttons) would solve it for PS2/3 emulation.

**Comment by nefarius** [comment]
[See here](https://forums.pcsx2.net/Thread-Native-Windows-Bluetooth-drivers-for-PlayStation-3-Peripherals?pid=607858#pid607858), I've started on that but currently lack the resources to continue.

**Comment by Rast1234** [comment]
> how is it supposed to be played? Which controllers and axes are natively supported and how do you want it?

The game is originally from PS2 and ported to PS3. Both systems had controllers with pressure sensitive regular buttons (X O □ ∆ 🡄 🡆 🡅 🡇, start, select). The game is one of rare games which actually utilized this at the core of gameplay:

* press □ slightly = aim your gun
* press □ fully = shoot your gun

All other buttons and axes are used too, so there is not much room to rebind, you will lose some gameplay features.

**Comment by Ghaleon4** [comment]
If there's a limit to the core game that requires we sacrifice an axis, the best compromise I could think of in my own setup was a toggle that turns my 'borrowed' axis on/off.  That way, I can toggle between fixed/regular controls when it's time to use the sword later in the game!  I.e., you can get away with borrowing an axis through most of the game -it's just that the sword complicates things later on...
I'm lurking in discord now...!

**Comment by nefarius** [comment]
See #18
