### ISSUE TITLE
vibration continues even after the game has stopped giving the vibration output

### ISSUE THREAD

**Issue by driftywinds** [nefarius/Shibari#7]
my ds3 was connected on bluetooth and during rocket league, the vibration continued even when my car was stopped.

**Comment by nefarius** [comment]
Known bug.

**Comment by Mxt-dot** [comment]
Could you give us an estimate on when you will have time to look into this issue? Or what the current plan is? I quite like the easy of use, but this is a dealbreaker currently...
I wish I knew how to approach driver debugging then I would make some attempts on my own.

Don't make me go back to ScpDriver, I beg you :D

Edit: It seems to happen spradically and is resolved after another vibration input. While the controller is stuck vibrating, it continues to do so even after a disconnect from the shibari server. The controller doesn't seem to respond to any input anymore and I can't turn it off until I restart the shibari server to stop the vibration.

**Comment by nefarius** [comment]
See #18
