### ISSUE TITLE
fake ds3 is assigned controller 1 instead of 2

### ISSUE THREAD

**Issue by driftywinds** [nefarius/Shibari#8]
i have 1 original ds3 and 1 fake ds3 and when i connect them both, they are assigned controller 1. Is there a way to assign the numbers on controllers?

**Comment by nefarius** [comment]
That's not supposed to happen, but you need to share way more details about your setup, the versions used, log outputs etc. before anybody can provide help.

**Comment by driftywinds** [comment]
Hey nefarious I've lost access to my setup but I will provide all the necessary information as soon as I can replicate the situation I was already in

**Comment by nefarius** [comment]
See #18
